apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-probe-404
  labels:
    environment: dev
  annotations:
    describe: annotation-value
    other: veri long annotation value, bla bla bla bla bla bla
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /404
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
