apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    environment: production
    team: internal-bisdev
    version: 1.1.0
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
