apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    environment: dev 
  annotations:
    manual-book: https://cms.id/manual-bok.pdf klik disini
    help: Hub Nomor WA ...
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
